export const data = [
    {
        url: "",
        text: "Play-Ground: Spider/web vibration, divination… for the terrestrial and cosmic web(s) of life",
        img: "/img-01.jpg",
        category: "Spider/Web",
        subtitle: "Exploring interconnectedness through vibrations",
        className: "font-bau",
    },
    {
        url: "",
        text: "Recording Aerosolar",
        img: "/img-02.jpg",
        category: "Aerocene",
        subtitle: "Documenting atmospheric journeys",
        className: "font-bau",
    },
    {
        url: "",
        text: "A letter from the communities of Salinas Grandes and Laguna de Guayatayoc to Pope Francis",
        img: "/img-03.jpg",
        category: "Community",
        subtitle: "Grassroots environmental advocacy",
        className: "font-bau",
    },
    {
        url: "",
        text: "Conviviality",
        img: "/img-04.jpg",
        category: "Community",
        subtitle: "Practices of collective existence",
        className: "font-bau",
    },
    {
        url: "",
        text: "ANIMA∞LE",
        img: "/img-05.jpg",
        category: "Aerocene",
        subtitle: "Human-animal-air relationships",
        className: "font-bau",
    },
    {
        url: "",
        text: "Cosmic Threads",
        img: "/img-06.jpg",
        category: "Cosmic",
        subtitle: "Celestial pattern explorations",
        className: "font-bau",
    },
    {
        url: "",
        text: "Aerocene Seoul",
        img: "/img-07.jpg",
        category: "Aerocene",
        subtitle: "Urban atmospheric interventions",
        className: "font-bau",
    },
    {
        url: "",
        text: "Live(s) on Air",
        img: "/img-08.jpg",
        category: "Aerocene",
        subtitle: "Atmospheric existence studies",
        className: "font-bau",
    },
    {
        url: "",
        text: "Worldings",
        img: "/img-09.jpg",
        category: "Cosmic",
        subtitle: "World-making practices",
        className: "font-bau",
    },
    {
        url: "",
        text: "Radical Playgrounds",
        img: "/img-10.jpg",
        category: "Play",
        subtitle: "Reimagining social spaces",
        className: "font-bau",
    },
    {
        url: "",
        text: "Fly with Pacha, Into the Aerocene",
        img: "/img-11.jpg",
        category: "Aerocene",
        subtitle: "Indigenous cosmological flights",
        className: "font-bau",
    },
    {
        url: "",
        text: "Complementarities",
        img: "/img-12.jpg",
        category: "Spider/Web",
        subtitle: "Inter-species coexistence",
        className: "font-bau",
    },
    {
        url: "",
        text: "Life(s) of webs, arachnophobias, arachnophilias, and other stories",
        img: "/img-13.jpg",
        category: "Spider/Web",
        subtitle: "Arachnid-human relationships",
        className: "font-bau",
    },
    {
        url: "",
        text: "AnarcoAracnoAnacroArcano",
        img: "/img-14.jpg",
        category: "Spider/Web",
        subtitle: "Anarchic web architectures",
        className: "font-bau",
    },
    {
        url: "",
        text: "Corona Australis 38.39",
        img: "/img-15.jpg",
        category: "Cosmic",
        subtitle: "Stellar constellation studies",
        className: "font-bau",
    },
    {
        url: "",
        text: "Life(s) of Webs",
        img: "/img-01.jpg",
        category: "Spider/Web",
        subtitle: "Interspecies web architectures",
        className: "font-bau",
    },
    {
        url: "",
        text: "Cloud Cities: mise-en-Aéroscène",
        img: "/img-02.jpg",
        category: "Aerocene",
        subtitle: "Floating urban imaginaries",
        className: "font-bau",
    },
    {
        url: "",
        text: "Web(s) of Life",
        img: "/img-03.jpg",
        category: "Spider/Web",
        subtitle: "Ecological interdependence",
        className: "font-bau",
    },
    {
        url: "",
        text: "Tomás Saraceno in collaboration: Web(s) of Life",
        img: "/img-04.jpg",
        category: "Spider/Web",
        subtitle: "Collaborative web installations",
        className: "font-bau",
    },
    {
        url: "",
        text: "Spiders in Motion, Rainy Commotion",
        img: "/img-05.jpg",
        category: "Spider/Web",
        subtitle: "Arachnid behavioral studies",
        className: "font-bau",
    },
    {
        url: "",
        text: "Aerocene Newspaper II",
        img: "/img-06.jpg",
        category: "Aerocene",
        subtitle: "Atmospheric community news",
        className: "font-bau",
    },
    {
        url: "",
        text: "Crux Australis 68.0",
        img: "/img-07.jpg",
        category: "Cosmic",
        subtitle: "Southern constellation explorations",
        className: "font-bau",
    },
    {
        url: "",
        text: "Entangled Air",
        img: "/img-08.jpg",
        category: "Aerocene",
        subtitle: "Atmospheric interconnectedness",
        className: "font-bau",
    },
    {
        url: "",
        text: "Oceans of Air",
        img: "/img-09.jpg",
        category: "Aerocene",
        subtitle: "Atmospheric fluid dynamics",
        className: "font-bau",
    },
    {
        url: "",
        text: "Silent Autumn",
        img: "/img-10.jpg",
        category: "Cosmic",
        subtitle: "Celestial seasonal transitions",
        className: "font-bau",
    },
    {
        url: "",
        text: "Aerocene: Free the Air. “Orbit-s” For a Post-Fossil Fuel Era",
        img: "/img-11.jpg",
        category: "Aerocene",
        subtitle: "Post-carbon flight manifesto",
        className: "font-bau",
    },
    {
        url: "",
        text: "Particular Matter(s)",
        img: "/img-12.jpg",
        category: "Aerocene",
        subtitle: "Atmospheric particle studies",
        className: "font-bau",
    },
    {
        url: "",
        text: "From Arachnophobia to Arachnophilia",
        img: "/img-13.jpg",
        category: "Spider/Web",
        subtitle: "Changing perceptions of spiders",
        className: "font-bau",
    },
    {
        url: "",
        text: "Inter + Play 2",
        img: "/img-14.jpg",
        category: "Play",
        subtitle: "Interactive spatial experiments",
        className: "font-bau",
    },
    {
        url: "",
        text: "Zonal Harmonic Constellation 170,000; 220,000",
        img: "/img-15.jpg",
        category: "Cosmic",
        subtitle: "Cosmic resonance mapping",
        className: "font-bau",
    },
    {
        url: "",
        text: "we do not all breathe the same air",
        img: "/img-01.jpg",
        category: "Aerocene",
        subtitle: "Atmospheric justice discourse",
        className: "font-bau",
    },
    {
        url: "",
        text: "Du sol au soleil",
        img: "/img-02.jpg",
        category: "Cosmic",
        subtitle: "Earth-sun interconnections",
        className: "font-bau",
    },
    {
        url: "",
        text: "Webs of Life",
        img: "/img-03.jpg",
        category: "Spider/Web",
        subtitle: "Interspecies network theories",
        className: "font-bau",
    },
    {
        url: "",
        text: "Museo Aero Solar: for an Aerocene era",
        img: "/img-04.jpg",
        category: "Aerocene",
        subtitle: "Community-built solar museum",
        className: "font-bau",
    },
    {
        url: "",
        text: "How to hear the universe in a spider/web: A live concert for/by invertebrate rights",
        img: "/img-05.jpg",
        category: "Spider/Web",
        subtitle: "Arachnid sonic vibrations",
        className: "font-bau",
    },
    {
        url: "",
        text: "Climate Crisis, a Crisis of Imagination",
        img: "/img-06.jpg",
        category: "Community",
        subtitle: "Reimagining climate futures",
        className: "font-bau",
    },
    {
        url: "",
        text: "Life(s) of Webs, publication launch at Palazzo Ducale",
        img: "/img-07.jpg",
        category: "Spider/Web",
        subtitle: "Arachnological research unveiling",
        className: "font-bau",
    },
    {
        url: "",
        text: "In Conversation: Tomás Saraceno",
        img: "/img-08.jpg",
        category: "Community",
        subtitle: "Artist dialogue series",
        className: "font-bau",
    },
    {
        url: "",
        text: "Art Collaboration Kyoto, Online Artist Talk",
        img: "/img-09.jpg",
        category: "Community",
        subtitle: "Cross-cultural artistic exchange",
        className: "font-bau",
    },
    {
        url: "",
        text: "Aerocene Forum",
        img: "/img-10.jpg",
        category: "Aerocene",
        subtitle: "Atmospheric philosophy symposium",
        className: "font-bau",
    },
];
